### ISSUE TITLE
offset() terms not recognised?

### ISSUE THREAD

**Issue by bzlato** [pachamaltese/eflm#1]
Hello

Ran this test case on a large dataset on Rstudio server. The stats::glm() equivalent works fine however the below code failes.

We always run glm() with offsets so this is pretty mission critical.

This is the most simple model I tried, a more complex one also failed with the same error

_**Error in offset(log(expectednum_rate2)) : 
  object 'expectednum_rate2' not found**_

```r
Model1e <-
  eglm(actualnum ~ offset(log(expectednum_rate2)) + offset(log(exposednum)), family = poisson(link = "log"),
                      data = US_grp_dta) 
```

**Comment by pachadotdev** [comment]
hi @bzlato 
sorry for the late reply, this week I re-wrote 90% of the code
do you have a mininal reproducible example? this can be of *great* help for the new released version

**Comment by bzlato** [comment]
Hi.

I was hoping to try your updated package on my data but the version on CRAN hasn't been updated yet right?

Not sure what a reprex can help with here, since it seemed to me that it was the offset() that was causing the problem rather than anything in the dataset?

If you still really need the reprex I can create toy data from my sensitive data.

Kind regards

Boris

**Comment by pachadotdev** [comment]
Thanks. I'd prefer no sensitive data, something like mtcars or similar.

**Comment by pachadotdev** [comment]
closing because of lack of response
