### ISSUE TITLE
Patrick 0.1.0 will have backwards incompatible changes

### ISSUE THREAD

**Issue by michaelquinn32** [pachamaltese/eflm#6]
Hi Pacha!

Thanks for using `patrick` for creating parameterized tests.

I am going to start the process of releasing a backwards incompatible change in the package.

*  In the past, the undocumented `test_name` parameter could be used to in cases data frames and as an argument for naming tests
*  I am moving this to a documented argument in `with_parameters_test_that()`. The argument is also getting the name `.test_name` in order to distinguish it from test cases passed by a user

In version 0.1.0, patrick will throw a warning about this change and rename input as appropriate. In the future, this warning will be dropped. Addressing it requires changing your use of `test_name` to `.test_name`.

Apologies for any inconvenience that this causes. Please let me know how else I can help.

Best wishes,
Michael

**Comment by pachadotdev** [comment]
> Hi Pacha!
> 
> Thanks for using `patrick` for creating parameterized tests.
> 
> I am going to start the process of releasing a backwards incompatible change in the package.
> 
>     * In the past, the undocumented `test_name` parameter could be used to in cases data frames and as an argument for naming tests
> 
>     * I am moving this to a documented argument in `with_parameters_test_that()`. The argument is also getting the name `.test_name` in order to distinguish it from test cases passed by a user
> 
> 
> In version 0.1.0, patrick will throw a warning about this change and rename input as appropriate. In the future, this warning will be dropped. Addressing it requires changing your use of `test_name` to `.test_name`.
> 
> Apologies for any inconvenience that this causes. Please let me know how else I can help.
> 
> Best wishes, Michael

thanks a lot! i'll change fixest PR as well

**Comment by pachadotdev** [comment]
@michaelquinn32 I finally patched this here https://github.com/pachadotdev/eflm/commit/db48ba88b9e14974d6212642a80990a7ee5f7a6e

My way of testing is a bit particular, the ~1000 tests are actually very compact
